services:
  timetablex:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timetablex
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Bangkok
    restart: unless-stopped
